baseURL = "https://www.ryannhg.com/"
languageCode = "en-us"
title = "ryan haskell-glatz."
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodeFences=true
[params]
  socialLinks = [
    { icon = "twitter", url = "https://www.twitter.com/ryan_nhg" },
    { icon = "github", url = "https://www.github.com/ryannhg" },
    { icon = "linkedin", url = "https://www.linkedin.com/in/ryan-haskell-glatz-3325b3a8/" }
  ]